### ISSUE TITLE
can not set the substance path.

### ISSUE THREAD

**Issue by PaulsonH** [stilobique/SubstanceBridge#16]
![qq 20180429173751](https://user-images.githubusercontent.com/35858134/39405227-2dd99716-4bd4-11e8-9818-e41241b8b2fc.png)

**Comment by stilobique** [comment]
Hi,
can you give me more information ?

- Your Operating System (OS), WIndows 10 ?
- You work with a Blender Steam, a zip version or an installer package ?
- You have download the latest version ?

[Have you try with a other version ?](https://github.com/stilobique/SubstanceBridge/releases) No error or message inside your console (Windows, Toggle System Consol) or your Info Panel ?

**Comment by PaulsonH** [comment]
WIN10  BLENDER 2.79b

**Comment by PaulsonH** [comment]
steam and latest version

**Comment by PaulsonH** [comment]
in fact both steam version and offical version can not set the path

**Comment by PaulsonH** [comment]
I  go try other version feedback later

**Comment by PaulsonH** [comment]
0.54 still not

**Comment by stilobique** [comment]
Alright, and you language operating ? I thinks it's a simple issue with the encodage file and path. I'm look to fix quickly this error.

**Comment by PaulsonH** [comment]
Chinese

**Comment by PaulsonH** [comment]
is that the language problem?

**Comment by PaulsonH** [comment]
ok seem is the language problem ,I change my whole system to English and path setting appear. 
Hope you can fix it thanks~~

**Comment by stilobique** [comment]
@PaulsonH i'm look to make a new branch with this error, i'm send you a new version with the fix when it's done.

**Comment by PaulsonH** [comment]
OK~thanks

**Comment by stilobique** [comment]
Can you try with this version ?
[SubstanceBridge.zip](https://github.com/stilobique/SubstanceBridge/files/1960084/SubstanceBridge.zip)

**Comment by PaulsonH** [comment]
how to install it .... I install it from file but it not appaer

**Comment by PaulsonH** [comment]
SubstanceBridge-master.zip   can be install by Install addon from file .
SubstanceBridge.zip doesn't work

**Comment by stilobique** [comment]
Arf, i have one error -just one moment plz :)

**Comment by stilobique** [comment]
Alright, i need to clean my folder ; now it's ok to install it ; before look inside your Addon folder -somethings like that "C:\Users\ReplaceYourSessionUserName\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons - and remove all substance bridge folder, addon_updater.py and addon_updater_ops.py if you have this files of course.

[SubstanceBridge.zip](https://github.com/stilobique/SubstanceBridge/files/1960166/SubstanceBridge.zip)

**Comment by PaulsonH** [comment]
ok it works✔ thanks

**Comment by stilobique** [comment]
Good 👍 
I can close this topic ?

**Comment by PaulsonH** [comment]
yes~

**Comment by PaulsonH** [comment]
wait

**Comment by PaulsonH** [comment]
i have a problem 
![qq 20180430212858](https://user-images.githubusercontent.com/35858134/39429427-75a08e8a-4cbd-11e8-9f07-241539aa1171.png)
what is this for? every time i press this it will start a new substance

**Comment by PaulsonH** [comment]
and loss all the texture  substance 2018

**Comment by PaulsonH** [comment]
maybe i need to start a new issue

**Comment by stilobique** [comment]
When you make your first export you create a new file, you need to select a path to select your .spp files ; i need to make a video to be more clear ^^ . 

However, you can find how to use with this Gif.
https://raw.githubusercontent.com/wiki/stilobique/SubstanceBridge/ressources/Demonstration.gif

If you don't unterstand how to used it yes, make a new issues and i'm look how to fix or make more explain on the Wiki.

**Comment by PaulsonH** [comment]
ok ~ i understand it . they both have to save a flie.or will not work

**Comment by PaulsonH** [comment]
I have one more question .Is that once you exprot the mesh, you can't add new mesh to it?
 I add a new mesh and texture is mess 
![2](https://user-images.githubusercontent.com/35858134/39461452-4fcee7da-4d3d-11e8-8e5d-e1bb51e8857c.png)
![1](https://user-images.githubusercontent.com/35858134/39461459-54c1f106-4d3d-11e8-979e-be43fc49d5d8.png)

**Comment by stilobique** [comment]
If you have add this mesh inside your Texture Set list the mesh take a texture, however you need to paint on your mesh, if you update your UV painter try to keep your paint and work arround the same placement -on the next step i think look to use the GLTF and the SUbstance Live to simplify the process, but i need to take the time to make it :) .

**Comment by PaulsonH** [comment]
English not well still dont understand how to do . O-o
